version: '2'
services:
  mysql:
    tty: true
    image: eosystems/mysql-eozkill
    volumes_from:
      - storage-mysql
    ports:
      - "13506:3306"
    networks:
      - kibana_net
    container_name: mysql-eozkill
    build: build/mysql-eozkill
    environment:
      MYSQL_ROOT_PASSWORD: password

  storage-mysql:
    tty: true
    image: eosystems/storage-mysql-eozkill
    #build: build/storage-mysql-eozkill
    container_name: storage-mysql-eozkill

  eozkill:
    #tty: true
    image: eosystems/eozkill
    volumes_from:
      - storage-eozkill
    container_name: app-eozkill
    networks:
      - kibana_net
    depends_on:
      - elasticsearch
    build:
      context: build/eozkill
      args:
        gitbranch: "master"
    ports:
      - "13200:3000"
    links:
      - mysql

  storage-eozkill:
    tty: true
    image: eosystems/storage-eozkill
    #build: build/storage-eozkill
    container_name: storage-eozkill

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch
    environment:
      - cluster.name=dev-kibana-cluster
      - node.name=dev-kibana-01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
      - xpack.monitoring.history.duration=1d
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    memswap_limit: 2g
    cap_add:
      - IPC_LOCK
    volumes:
      - es_data1:/usr/share/elasticsearch/data1
    ports:
      - 9200:9200
    networks:
      - kibana_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      XPACK_MONITORING_ELASTICSEARCH_URL: "http://elasticsearch:9200"
      XPACK_SECURITY_ENABLED: "false"
    ports:
     - 5601:5601
    networks:
      - kibana_net
    mem_limit: 2g
    memswap_limit: 2g
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  es_data1:
    driver: local

networks:
  kibana_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.99.0.0/24
          gateway: 172.99.0.1
